move to new env style setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,5 +1,5 @@
 #!/bin/zsh
-# shellcheck disable=SC2154,SC2086
+# shellcheck disable=SC2154,SC2086,SC2088
 
 set -u
 
@@ -221,6 +221,27 @@ append_shell_hook() {
   fi
 }
 
+configure_zshenv() {
+  (( EDIT_SHELL == 1 )) || return 0
+
+  local zshenv="${HOME}/.zshenv"
+  local hook="source ${MY_PATH}/turbo_zsh/init.zsh"
+
+  [[ -f "$zshenv" ]] || touch "$zshenv"
+  grep -Fq "$hook" "$zshenv" && {
+    info "~/.zshenv already includes turbo_zsh"
+    return 0
+  }
+
+  if ask_yes_no "Append turbo_zsh startup line to ${zshenv}?"; then
+    printf "\n# turbo_zsh - provides required functions for ohm\n%s\n" "$hook" >> "$zshenv"
+    info "Added turbo_zsh hook to ${zshenv}"
+  else
+    warn "Skipped .zshenv update. Add this manually:"
+    echo "  $hook"
+  fi
+}
+
 run_doctor() {
   info "Running post-install checks"
   "${MY_PATH}/ohm" doctor || return 1
@@ -233,6 +254,7 @@ main() {
   preflight
   ensure_dependencies
   configure_user_files
+  configure_zshenv
   append_shell_hook
   run_doctor
   info "Done. Restart shell and run: m"
